### ISSUE TITLE
All parameters ignored if use_gravatar or gravatar_hashed are set to true

### ISSUE THREAD

**Issue by jykntr** [syndbg/flask-robohash#2]
The purpose of the two gravatar flags for Robohash are to allow the image returned to be the users Gravatar image if they have one, or a Robohash image if they don't.  Currently flask-robohash ignores all other parameters passed in if ```use_gravatar``` or ```gravatar_hashed``` are true.  This means that if a Gravatar image is configured things will work correct except for the size of the image, and that if there isn't a Gravatar image configured none of the Robohash parameters will be respected.

Examples:
* This URL defaults to the hash's Gravatar image because it has been setup and also respects the size passed in:
https://robohash.org/620050a4db5104bae758cd75171d64ca?gravatar=hashed&size=50x50

* This URL defaults back to a robohash image because the hash isn't setup in Gravatar yet and still respects the size:
https://robohash.org/620050a4db5104bae758cd75171d64cb?gravatar=hashed&size=50x50

But with the usage ```{{ user.first_name | robohash(x=50, y=50, gravatar_hashed=True) }}```, these are the resulting URLs which obviously doesn't respect the size in either case (or any other parameters that could be passed in):
https://robohash.org/620050a4db5104bae758cd75171d64ca?gravatar=hashed
https://robohash.org/620050a4db5104bae758cd75171d64cb?gravatar=hashed

If you would like some help, I'm willing to submit a pull request.  Thanks!

**Comment by syndbg** [comment]
Oh. I was certain that robohash.org had the same behavior as the one I implemented in `flask-robohash`. 
I'll write tests and implement the functionality as you described.

Thanks for the feedback and being descriptive! This may take two days, since it's Easter holidays. Cheers :yellow_heart:

**Comment by jykntr** [comment]
Just for fun I decided to give you my solution.  Hopefully things look good, I updated tests as well.
